<?php

  namespace App\Konstant;

  class CouchbaseMemIds
  {
    const CITIES = 'CITIES';

    const VENUES_GETBYCITYURLNAME = 'VENUES_GETBYCITYURLNAME_{{CITY_URLNAME}}';

    const EVENTS_GETEVENTSBYTIME = 'EVENTS_GETEVENTSBYTIME_{{CITY_URLNAME}}';
    const EVENTS_GETBYURLNAME = 'EVENTS_GETBYURLNAME_{{URLNAME}}';
    const EVENTS_GETBYVENUEURLNAME = 'EVENTS_GETBYVENUEURLNAME_{{VENUE_URLNAME}}';
  }
